version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - cheon_1_network
    volumes:
      - cheon_1_media:/data/media/
      - cheon_1_static:/data/static/
      - cheon_1_log:/var/log/nginx/
      - /home/hokoro123/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
    - cheon_1_log:/var/log/nginx/
    ports:
    - 7890:7890
    command: /var/log/nginx/cheon_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html


  django:
    image: cheondjango:5
    networks:
      - cheon_1_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

    volumes:
      - cheon_1_media:/home/cheon01copy/media/
      - cheon_1_static:/home/cheon01copy/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - cheon_1_network
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    volumes:
      - cheon_1_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  cheon_1_network:

volumes:
  cheon_1_media:
  cheon_1_static:
  cheon_1_mariadb:
  cheon_1_log:


secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
